services:
  database: 
    image: postgres
    container_name: desafio-react-jr
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata: 
    driver: local
  